### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by yochananmarqos** [shaquibimdad/gnome_ext_volume_boost#1]
Unless I missed something, this seems overkill just to run one command:

```
gsettings set org.gnome.desktop.sound allow-volume-above-100-percent 'true'
```

**Comment by shaquibimdad** [comment]
> Unless I missed something, this seems overkill just to run one command:
> 
> ```
> gsettings set org.gnome.desktop.sound allow-volume-above-100-percent 'true'
> ```

pactl set-sink-volume sinkname x%  
this can also work with many other alternative but not everyone have time to dig

**Comment by shaquibimdad** [comment]
> I've always had this setting set since it used to be an option in GNOME Tweaks. I've never had to use any other command because that's all it did.
> 
> > pactl set-sink-volume sinkname x%
> > this can also work with many other alternative but not everyone have time to dig
> 
> Sorry, I'm not following.

Since the option to enable amplification isn't available in GNOME Tweaks anymore, this extension was created to fill that gap as simple as that

**Comment by yochananmarqos** [comment]
> Since the option to enable amplification isn't available in GNOME Tweaks anymore, this extension was created to fill that gap

Fair enough.

However, that doesn't answer my query about your previous response. Your extension doesn't call `pactl` and I have no clue what "may other alternative" means.

**Comment by shaquibimdad** [comment]
> However, that doesn't answer my query about your previous response. Your extension doesn't call `pactl` and I have no clue what "many other alternative" means.

Actually made a whole new extension which is not bounded by gsetting and works independently and also have manual call to pactl and can boost volume to any upper and lower limits unlike gnome max 153% and i will make this extension public once gnome remove their volume boost sometime in the future

``` many other alternatives ``` refers to different ways you can boost volume there is not just `pactl` and `gsetting`  you can use amixer, pamixer or can connect to home theatre for more robust amplification :wink:  
> 
> Tip: If you had a good README, I never would have had a reason to create an issue. 😉

Sure i will add one

**Comment by yochananmarqos** [comment]
I see. I'll close this then. Thanks for responding.
