### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by ricolxwz** [shaquibimdad/gnome_ext_volume_boost#2]
After uninstalling, the functionality can not be removed in the panel: 
![image](https://github.com/shaquibimdad/gnome_ext_volume_boost/assets/92409532/2864751d-a42a-4eda-83cc-af3128fbebfe)

**Comment by shaquibimdad** [comment]
fixed in [this commit](https://github.com/shaquibimdad/gnome_ext_volume_boost/commit/fd58eda399dd97b00c5a6b886eb66176959f092f)
